// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using orenji_backend.Data;

namespace orenji_backend.Data.Migrations
{
    [DbContext(typeof(OrenjiContext))]
    [Migration("20230108153252_MoreVariedProducts")]
    partial class MoreVariedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("orenji_backend.Common.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88012fe0-114f-4a36-858a-49e6cfe92650"),
                            Email = "a@a.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "a",
                            PhoneNumber = "11234567890",
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("cc923a8d-b099-4a94-a6af-0dfbea9221fc"),
                            Email = "b@b.com",
                            FirstName = "Joe",
                            LastName = "Biden",
                            Password = "b",
                            PhoneNumber = "21234567890",
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("f269d8a3-37e3-4062-bcd9-bb8ae4031a3c"),
                            Email = "c@c.com",
                            FirstName = "James",
                            LastName = "Howard",
                            Password = "c",
                            PhoneNumber = "31234567890",
                            Size = "XL"
                        });
                });

            modelBuilder.Entity("orenji_backend.Common.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AudienceType")
                        .HasColumnType("longtext");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9442467f-055d-4814-8411-617d48501cf7"),
                            AudienceType = "Male",
                            Company = "The Cool Company",
                            Name = "Cool Pants",
                            Price = 4.9900000000000002,
                            Size = "M",
                            Type = "Pants"
                        },
                        new
                        {
                            Id = new Guid("18765e76-5367-47b1-a743-c8582b91a8af"),
                            AudienceType = "Male",
                            Company = "The Quirky Company ",
                            Name = "Quirky Pants",
                            Price = 9.9900000000000002,
                            Size = "L",
                            Type = "Pants"
                        },
                        new
                        {
                            Id = new Guid("1d232014-b9aa-49ae-9584-9dee7605e81d"),
                            AudienceType = "Female",
                            Company = "The Lax Company ",
                            Name = "Lax Pants",
                            Price = 1.99,
                            Size = "M",
                            Type = "Pants"
                        },
                        new
                        {
                            Id = new Guid("76a0262d-a863-4bdb-8a61-9e5e0babafbf"),
                            AudienceType = "Male",
                            Company = "The Modest Company",
                            Name = "Modest Shirt",
                            Price = 12.99,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("35418881-2aa7-4743-b3c2-d1f498c121ab"),
                            AudienceType = "Male",
                            Company = "The Calm Company",
                            Name = "Calm Shirt",
                            Price = 19.989999999999998,
                            Size = "L",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("1228a42e-20bc-4caf-919c-66ed1eaa4d34"),
                            AudienceType = "Female",
                            Company = "The Modest Company",
                            Name = "Timid Shirt",
                            Price = 24.989999999999998,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("50256ef6-bc7a-475f-b2c5-179e10b2bf8c"),
                            AudienceType = "Female",
                            Company = "The Adamant Company",
                            Name = "Adamant Shirt",
                            Price = 64.989999999999995,
                            Size = "S",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("20d922d0-8117-4906-8bef-6acf54aad172"),
                            AudienceType = "Genderless",
                            Company = "The Lonely Company",
                            Name = "Lonely Shirt",
                            Price = 14.99,
                            Size = "XS",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("7d9bd902-da63-44f9-8536-d014ea5fb1ee"),
                            AudienceType = "Genderless",
                            Company = "The Jolly Company",
                            Name = "Jolly Shirt",
                            Price = 47.990000000000002,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("d7237b8a-d35c-467b-82ac-06bf10e88ffb"),
                            AudienceType = "Genderless",
                            Company = "The Brave Company",
                            Name = "Brave Shirt",
                            Price = 34.990000000000002,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("3964e013-24c9-43ae-a6ae-b72c57660585"),
                            AudienceType = "Male",
                            Company = "The Adamant Company",
                            Name = "Adamant Shirt",
                            Price = 12.99,
                            Size = "M",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("92bdb1a3-f319-4b6d-99b5-ac99bfbaf0da"),
                            AudienceType = "Female",
                            Company = "The Docile Company",
                            Name = "Docile Shirt",
                            Price = 19.989999999999998,
                            Size = "M",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("899faa01-bba9-42f8-bda8-4ae7ac340638"),
                            AudienceType = "Female",
                            Company = "The Lonely Company",
                            Name = "Lonely Shirt",
                            Price = 24.989999999999998,
                            Size = "S",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("46b8eb91-0960-4904-beaa-a011e11d7e27"),
                            AudienceType = "Female",
                            Company = "The Timid Company",
                            Name = "Timid Shirt",
                            Price = 64.989999999999995,
                            Size = "L",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("9a72af1b-e958-499a-acc3-50a5257c25a2"),
                            AudienceType = "Male",
                            Company = "The Bold Company",
                            Name = "Bold Shirt",
                            Price = 14.99,
                            Size = "L",
                            Type = "Shoe"
                        });
                });

            modelBuilder.Entity("orenji_backend.Common.Models.ProductInCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("fAccount")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("fProduct")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("ProductInCart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6abf797-3eb7-4b0a-a9ae-8859e09076bb"),
                            fAccount = new Guid("88012fe0-114f-4a36-858a-49e6cfe92650"),
                            fProduct = new Guid("3964e013-24c9-43ae-a6ae-b72c57660585")
                        },
                        new
                        {
                            Id = new Guid("3c0b23db-6b47-4363-a79c-20291a5052ab"),
                            fAccount = new Guid("88012fe0-114f-4a36-858a-49e6cfe92650"),
                            fProduct = new Guid("92bdb1a3-f319-4b6d-99b5-ac99bfbaf0da")
                        },
                        new
                        {
                            Id = new Guid("e264ded7-b6bd-4f9b-b88d-d0d88848b67a"),
                            fAccount = new Guid("88012fe0-114f-4a36-858a-49e6cfe92650"),
                            fProduct = new Guid("899faa01-bba9-42f8-bda8-4ae7ac340638")
                        },
                        new
                        {
                            Id = new Guid("23611263-e40a-4d29-9c21-da86a8431349"),
                            fAccount = new Guid("88012fe0-114f-4a36-858a-49e6cfe92650"),
                            fProduct = new Guid("46b8eb91-0960-4904-beaa-a011e11d7e27")
                        },
                        new
                        {
                            Id = new Guid("c0ea0292-34a3-4493-b2b8-9181b5668073"),
                            fAccount = new Guid("88012fe0-114f-4a36-858a-49e6cfe92650"),
                            fProduct = new Guid("9a72af1b-e958-499a-acc3-50a5257c25a2")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
