// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using orenji_backend.Data;

namespace orenji_backend.Data.Migrations
{
    [DbContext(typeof(OrenjiContext))]
    [Migration("20230108134301_ProductChanges")]
    partial class ProductChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("orenji_backend.Common.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46b03f62-5016-48a1-bd41-aa3d639e6673"),
                            Email = "a@a.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "a",
                            PhoneNumber = "11234567890",
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("7903c56e-5785-45ed-b2b7-12cc0189b384"),
                            Email = "b@b.com",
                            FirstName = "Joe",
                            LastName = "Biden",
                            Password = "b",
                            PhoneNumber = "21234567890",
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("b8a175d9-49e1-4609-b7b2-ec6877d5fced"),
                            Email = "c@c.com",
                            FirstName = "James",
                            LastName = "Howard",
                            Password = "c",
                            PhoneNumber = "31234567890",
                            Size = "XL"
                        });
                });

            modelBuilder.Entity("orenji_backend.Common.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AudienceType")
                        .HasColumnType("longtext");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("168d4936-0a69-443c-88cf-61223a0eaccc"),
                            AudienceType = "Male",
                            Company = "The Cool Company",
                            Name = "Cool Pants",
                            Price = 4.9900000000000002,
                            Size = "M",
                            Type = "Pants"
                        },
                        new
                        {
                            Id = new Guid("a8f343eb-ddcd-4dd1-b7f0-5384c5c99f8a"),
                            AudienceType = "Male",
                            Company = "The Quirky Company ",
                            Name = "Quirky Pants",
                            Price = 9.9900000000000002,
                            Size = "M",
                            Type = "Pants"
                        },
                        new
                        {
                            Id = new Guid("171b609b-6d5b-4b3e-9f28-97e451ad29a1"),
                            AudienceType = "Male",
                            Company = "The Lax Company ",
                            Name = "Lax Pants",
                            Price = 1.99,
                            Size = "M",
                            Type = "Pants"
                        },
                        new
                        {
                            Id = new Guid("738fc24d-668d-423b-ab22-bb61fc2c7656"),
                            AudienceType = "Male",
                            Company = "The Modest Company",
                            Name = "Modest Shirt",
                            Price = 12.99,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("43165ec8-4aa0-48aa-a0ed-6587fea0f916"),
                            AudienceType = "Male",
                            Company = "The Calm Company",
                            Name = "Calm Shirt",
                            Price = 19.989999999999998,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("2977fca5-ba72-4709-8c3d-1d95351279d1"),
                            AudienceType = "Male",
                            Company = "The Modest Company",
                            Name = "Timid Shirt",
                            Price = 24.989999999999998,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("4b717fdd-a770-4bcd-bd2e-6fdde86a0350"),
                            AudienceType = "Male",
                            Company = "The Adamant Company",
                            Name = "Adamant Shirt",
                            Price = 64.989999999999995,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("6a8f73be-5bd6-495c-9014-d2857c031343"),
                            AudienceType = "Male",
                            Company = "The Lonely Company",
                            Name = "Lonely Shirt",
                            Price = 14.99,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("a9adbdc1-fc2a-4dac-b3fc-8b93ede1c947"),
                            AudienceType = "Male",
                            Company = "The Jolly Company",
                            Name = "Jolly Shirt",
                            Price = 47.990000000000002,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("af817a7f-90c6-410c-932e-514274761baf"),
                            AudienceType = "Male",
                            Company = "The Brave Company",
                            Name = "Brave Shirt",
                            Price = 34.990000000000002,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("5a417974-a42c-4445-bdcc-cf22d19fb4a1"),
                            AudienceType = "Male",
                            Company = "The Adamant Company",
                            Name = "Adamant Shirt",
                            Price = 12.99,
                            Size = "M",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("d3eac698-92c0-4fff-aa3c-3b943d057d5f"),
                            AudienceType = "Male",
                            Company = "The Docile Company",
                            Name = "Docile Shirt",
                            Price = 19.989999999999998,
                            Size = "M",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("5276a148-eee5-4523-9a53-166d6681c812"),
                            AudienceType = "Male",
                            Company = "The Lonely Company",
                            Name = "Lonely Shirt",
                            Price = 24.989999999999998,
                            Size = "M",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("0b516438-3831-4666-a200-75dc5a82c78f"),
                            AudienceType = "Male",
                            Company = "The Timid Company",
                            Name = "Timid Shirt",
                            Price = 64.989999999999995,
                            Size = "M",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("e7bb15e3-b88c-4c94-b1dc-7592146a9d0a"),
                            AudienceType = "Male",
                            Company = "The Bold Company",
                            Name = "Bold Shirt",
                            Price = 14.99,
                            Size = "M",
                            Type = "Shoe"
                        });
                });

            modelBuilder.Entity("orenji_backend.Common.Models.ProductInCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("fAccount")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("fProduct")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("ProductInCart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad323092-4519-4879-ac8e-78744df6fa96"),
                            fAccount = new Guid("46b03f62-5016-48a1-bd41-aa3d639e6673"),
                            fProduct = new Guid("5a417974-a42c-4445-bdcc-cf22d19fb4a1")
                        },
                        new
                        {
                            Id = new Guid("abbb9791-0655-4c27-89d8-235be9382dca"),
                            fAccount = new Guid("46b03f62-5016-48a1-bd41-aa3d639e6673"),
                            fProduct = new Guid("d3eac698-92c0-4fff-aa3c-3b943d057d5f")
                        },
                        new
                        {
                            Id = new Guid("5b172a92-01a5-4dd4-985f-b465ede9148c"),
                            fAccount = new Guid("46b03f62-5016-48a1-bd41-aa3d639e6673"),
                            fProduct = new Guid("5276a148-eee5-4523-9a53-166d6681c812")
                        },
                        new
                        {
                            Id = new Guid("2f21d87a-fbbd-494a-b6a7-f4a836fbcb06"),
                            fAccount = new Guid("46b03f62-5016-48a1-bd41-aa3d639e6673"),
                            fProduct = new Guid("0b516438-3831-4666-a200-75dc5a82c78f")
                        },
                        new
                        {
                            Id = new Guid("808e08dd-9b41-4e67-91bf-f3edcab2004a"),
                            fAccount = new Guid("46b03f62-5016-48a1-bd41-aa3d639e6673"),
                            fProduct = new Guid("e7bb15e3-b88c-4c94-b1dc-7592146a9d0a")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
