// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using orenji_backend.Data;

namespace orenji_backend.Data.Migrations
{
    [DbContext(typeof(OrenjiContext))]
    [Migration("20230115001956_AddedAccountRoles3")]
    partial class AddedAccountRoles3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("orenji_backend.Common.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("567cf2ec-f095-420f-8ed5-ad7fcbfcf50b"),
                            Email = "a@a.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "a",
                            PhoneNumber = "11234567890",
                            Role = "Administrator",
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("9a5de550-1e05-4f3c-a161-8708b18ab88c"),
                            Email = "b@b.com",
                            FirstName = "Joe",
                            LastName = "Biden",
                            Password = "b",
                            PhoneNumber = "21234567890",
                            Role = "User",
                            Size = "L"
                        },
                        new
                        {
                            Id = new Guid("35cf9275-009b-4335-bbcc-4f512486d403"),
                            Email = "c@c.com",
                            FirstName = "James",
                            LastName = "Howard",
                            Password = "c",
                            PhoneNumber = "31234567890",
                            Role = "User",
                            Size = "XL"
                        });
                });

            modelBuilder.Entity("orenji_backend.Common.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AudienceType")
                        .HasColumnType("longtext");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5a6b395-b75e-4343-ae1a-183e7c641771"),
                            AudienceType = "Male",
                            Company = "The Cool Company",
                            Name = "Cool Pants",
                            Price = 4.9900000000000002,
                            Size = "M",
                            Type = "Pants"
                        },
                        new
                        {
                            Id = new Guid("024f5426-2458-4273-991b-fb3863482e57"),
                            AudienceType = "Male",
                            Company = "The Quirky Company ",
                            Name = "Quirky Pants",
                            Price = 9.9900000000000002,
                            Size = "L",
                            Type = "Pants"
                        },
                        new
                        {
                            Id = new Guid("ad6446b6-ffd8-4c51-b496-158d6da4d5b4"),
                            AudienceType = "Female",
                            Company = "The Lax Company ",
                            Name = "Lax Pants",
                            Price = 1.99,
                            Size = "M",
                            Type = "Pants"
                        },
                        new
                        {
                            Id = new Guid("f1319c4f-2674-4e22-af38-48ca25c154fd"),
                            AudienceType = "Male",
                            Company = "The Modest Company",
                            Name = "Modest Shirt",
                            Price = 12.99,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("09089ee3-77dc-42a0-8b6e-2cb9b9593537"),
                            AudienceType = "Male",
                            Company = "The Calm Company",
                            Name = "Calm Shirt",
                            Price = 19.989999999999998,
                            Size = "L",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("c0d7a583-4bb5-481a-b1ae-c1c8a47f309f"),
                            AudienceType = "Female",
                            Company = "The Modest Company",
                            Name = "Timid Shirt",
                            Price = 24.989999999999998,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("219363f7-4997-4e96-89f0-99ec78c64ae9"),
                            AudienceType = "Female",
                            Company = "The Adamant Company",
                            Name = "Adamant Shirt",
                            Price = 64.989999999999995,
                            Size = "S",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("f6da7f5b-a446-42f4-9e2b-7abe0c24e9bb"),
                            AudienceType = "Genderless",
                            Company = "The Lonely Company",
                            Name = "Lonely Shirt",
                            Price = 14.99,
                            Size = "XS",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("98369b84-bd83-4853-ad78-0873e50f98aa"),
                            AudienceType = "Genderless",
                            Company = "The Jolly Company",
                            Name = "Jolly Shirt",
                            Price = 47.990000000000002,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("748d03d8-8d3c-4dcf-9d20-efb6fe389e66"),
                            AudienceType = "Genderless",
                            Company = "The Brave Company",
                            Name = "Brave Shirt",
                            Price = 34.990000000000002,
                            Size = "M",
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = new Guid("462814c3-6b78-4713-a67a-9780341f9b81"),
                            AudienceType = "Male",
                            Company = "The Adamant Company",
                            Name = "Adamant Shirt",
                            Price = 12.99,
                            Size = "M",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("439e84e1-8995-4876-a669-54649890e156"),
                            AudienceType = "Female",
                            Company = "The Docile Company",
                            Name = "Docile Shirt",
                            Price = 19.989999999999998,
                            Size = "M",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("682c75e0-eebe-457e-999b-3d24d0f4efd9"),
                            AudienceType = "Female",
                            Company = "The Lonely Company",
                            Name = "Lonely Shirt",
                            Price = 24.989999999999998,
                            Size = "S",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("1f61adac-beff-44ec-88a3-06c29ee45510"),
                            AudienceType = "Female",
                            Company = "The Timid Company",
                            Name = "Timid Shirt",
                            Price = 64.989999999999995,
                            Size = "L",
                            Type = "Shoe"
                        },
                        new
                        {
                            Id = new Guid("36336085-885b-4fda-8d45-0e79a6387469"),
                            AudienceType = "Male",
                            Company = "The Bold Company",
                            Name = "Bold Shirt",
                            Price = 14.99,
                            Size = "L",
                            Type = "Shoe"
                        });
                });

            modelBuilder.Entity("orenji_backend.Common.Models.ProductInCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("fAccount")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("fProduct")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("ProductInCart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c136025d-07a0-488b-864a-5de03a3d85b2"),
                            fAccount = new Guid("567cf2ec-f095-420f-8ed5-ad7fcbfcf50b"),
                            fProduct = new Guid("462814c3-6b78-4713-a67a-9780341f9b81")
                        },
                        new
                        {
                            Id = new Guid("be434191-663a-43b5-a796-56e301a951cd"),
                            fAccount = new Guid("567cf2ec-f095-420f-8ed5-ad7fcbfcf50b"),
                            fProduct = new Guid("439e84e1-8995-4876-a669-54649890e156")
                        },
                        new
                        {
                            Id = new Guid("48650102-88a8-4f2a-bc98-3c5a0c483149"),
                            fAccount = new Guid("567cf2ec-f095-420f-8ed5-ad7fcbfcf50b"),
                            fProduct = new Guid("682c75e0-eebe-457e-999b-3d24d0f4efd9")
                        },
                        new
                        {
                            Id = new Guid("4e4d5a15-9c91-45de-9b16-d0065b7d00db"),
                            fAccount = new Guid("567cf2ec-f095-420f-8ed5-ad7fcbfcf50b"),
                            fProduct = new Guid("1f61adac-beff-44ec-88a3-06c29ee45510")
                        },
                        new
                        {
                            Id = new Guid("fe517fe5-a26a-44e4-b143-5ac1755d31f3"),
                            fAccount = new Guid("567cf2ec-f095-420f-8ed5-ad7fcbfcf50b"),
                            fProduct = new Guid("36336085-885b-4fda-8d45-0e79a6387469")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
